### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by davidkhala** [yiwenlong/fabric-sdk-java-example#1]
Is it possible to add gradle configure files along with existing pom.xml?

**Comment by yiwenlong** [comment]
Hi, David
I think it's a good idea. I will add gradle configure files in this week.
Thank you very much for your suggestion.

By the way, this issue is first issue in my personal open source project. This is very meaningful to me.

**Comment by davidkhala** [comment]
**Open Source is the future** while

![](https://recruitingdaily.com/wp-content/uploads/sites/6/2017/02/quote-talk-is-cheap-show-me-the-code-linus-torvalds-45-66-13-e1487242875427.jpg)

**Comment by yiwenlong** [comment]
Hey, David
Here is the [code & document](https://github.com/yiwenlong/fabric-sdk-java-example). Hope useful to you.
